In [12]:
import numpy as np

a=np.array([1,3,2,5,4])

In [14]:

a,b=[10,20]
c=a+b
print(c)
print("Shape of Array b: ",b.shape)
r,c=b.shape
print("Row of Array b: ",r,"Columns of b: ",c)
ptint("Shape of Array a: ",a.shape,"Shape of Columns b: ",b.shape)

30


AttributeError: 'int' object has no attribute 'shape'

In [13]:
print("Sorted array k: ",np.sort(a))
print("Array in sorted order:",sorted(a))
print("Mean of array elements")
print(a.mean(),"\n")
print("Variance of array elements: ")
print(a.var(),"\n")
print("Standard deviation of array elements: ")
print(a.std(),"\n")


Sorted array k:  [1 2 3 4 5]
Array in sorted order: [1, 2, 3, 4, 5]
Mean of array elements
3.0 

Variance of array elements: 
2.0 

Standard deviation of array elements: 
1.4142135623730951 



In [15]:
a1=np.array([(1,2,3),(4,5,6)])
print("Zeroth row: ",a1[0])
print("First row: ",a1[1])
print("Second row,two values: ",a[1, :2])

Zeroth row:  [1 2 3]
First row:  [4 5 6]


TypeError: 'int' object is not subscriptable

In [ ]:
x=np.aaray([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
z=x[1:3,1:3]
print("After slicing, array becomes: ")
print (z)|
y=x[1:3,1:3]


WAP to change the value of following tuple:

(1,2,3,4,5,6)=>change 2 to 200

Boolean Indexing and Comparision of Array

In [17]:
x=np.array([1,2,3,4,5,6,7,8,9,10])
print("The items greater than 5 are: ")
print((x[x>5]))
m=np.array([2,7,4,7,9,4,7])
n=np.array([4,6,7,9,1,5,7])
print("Printing the comparision of elements")
print(m>n)

The items greater than 5 are: 
[ 6  7  8  9 10]
Printing the comparision of elements
[False  True False False  True False False]


In [18]:
x=np.array([1,2,3,4,5,6,7,8,9,10])
print("The items greater than 5 are: ")
print((x[x>5]))
m=np.array([2,7,4,7,9,4,7])
n=np.array([4,6,7,9,1,5,7])
print("Printing the comparision of elements")
print(m&n)

The items greater than 5 are: 
[ 6  7  8  9 10]
Printing the comparision of elements
[0 6 4 1 1 4 7]


In [ ]:
  3